# coding: utf-8

"""
    Uber API

    Move your app forward with the Uber API

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ModelDelta(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, position_delta=None, rotation_delta=None, scale_delta=None):
        """
        ModelDelta - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'position_delta': 'Vector3',
            'rotation_delta': 'Vector3',
            'scale_delta': 'Vector3'
        }

        self.attribute_map = {
            'position_delta': 'positionDelta',
            'rotation_delta': 'rotationDelta',
            'scale_delta': 'scaleDelta'
        }

        self._position_delta = position_delta
        self._rotation_delta = rotation_delta
        self._scale_delta = scale_delta


    @property
    def position_delta(self):
        """
        Gets the position_delta of this ModelDelta.


        :return: The position_delta of this ModelDelta.
        :rtype: Vector3
        """
        return self._position_delta

    @position_delta.setter
    def position_delta(self, position_delta):
        """
        Sets the position_delta of this ModelDelta.


        :param position_delta: The position_delta of this ModelDelta.
        :type: Vector3
        """

        self._position_delta = position_delta

    @property
    def rotation_delta(self):
        """
        Gets the rotation_delta of this ModelDelta.


        :return: The rotation_delta of this ModelDelta.
        :rtype: Vector3
        """
        return self._rotation_delta

    @rotation_delta.setter
    def rotation_delta(self, rotation_delta):
        """
        Sets the rotation_delta of this ModelDelta.


        :param rotation_delta: The rotation_delta of this ModelDelta.
        :type: Vector3
        """

        self._rotation_delta = rotation_delta

    @property
    def scale_delta(self):
        """
        Gets the scale_delta of this ModelDelta.


        :return: The scale_delta of this ModelDelta.
        :rtype: Vector3
        """
        return self._scale_delta

    @scale_delta.setter
    def scale_delta(self, scale_delta):
        """
        Sets the scale_delta of this ModelDelta.


        :param scale_delta: The scale_delta of this ModelDelta.
        :type: Vector3
        """

        self._scale_delta = scale_delta

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
